# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "no_intra_emphasis", "tables"]
highlighter: pygments

# Site settings
title: "HS 614"
description: > # this means to ignore newlines until "email:"
  Clinical Decision Support and Data Analytics

email: andrew.nguyen@usfca.edu
#blog logo
logo: "/assets/images/logo.png"
# blog cover
#cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
cover: "/assets/images/ipad-in-operating-room.png"

name: "Andrew Nguyen"
author: "Andrew Nguyen"
author_image: "/assets/images/author.png"

paginate: 20	

url: "http://usf-hs-614.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  #  - icon:	twitter
  #    url:	https://twitter.com/dirkfabisch
  #    desc: Follow me on twitter
  #    share_url: http://twitter.com/share
  #    share_title: ?text=
  #    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/usf-hs-614
    desc:	Course organization @ github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
